services:
  graphql:
    image: golang
    environment:
      - JWT_SECRET=supersecretkey
    volumes:
      - .:/go/src
    command: /bin/bash -c "cd src && go run *.go"
    ports:
    - 8080:8080
  mongo:
    image: mongo